runtime: php
    env: flex

    runtime_config:
      document_root: web
      front_controller_file: app.php
      
      env_variables:
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: duniya
  DB_USERNAME: root
  DB_PASSWORD: Raju@123
  DB_SOCKET: "/cloudsql/status-duniya:asia-south1-a:duniya2"

beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: "status-duniya:asia-south1-a:duniya2"
   
